import product1 from '../../assets/images/product-1.png';
import product2 from '../../assets/images/product-2.png';
import product3 from '../../assets/images/product-3.png';
import product4 from '../../assets/images/product-4.png';

export const saleProducts = [
  {
    id: 14,
    label: 'Casual Pant',
    description: 'Desc 1',
    pictures: [product1],
    stock: '1',
    tags: ['asas', 'sasa'],
    createdAt: '2023-03-23T05:58:09.383Z',
    updatedAt: '2023-03-23T05:58:09.383Z',
    details: {
      id: 17,
      price: 1000,
      offered_price: 900,
      currency: 'USD',
      size: 'Medium',
      condition: 'Poor',
      style: 'casual',
      colour: 'Blue',
      material: 'material-1',
      quantity_type: 'single',
    },
    sub_category: {
      id: 13,
      label: 'test_label',
      description: 'test_description',
      createdAt: '2023-03-19T14:21:59.394Z',
      updatedAt: '2023-03-19T14:21:59.394Z',
    },
    brand: {
      id: 3,
      label: 'Ali Baba',
      description:
        'Alibaba  connects buyers and sellers worldwide and offers a wide range of products, from consumer goods to industrial machinery.',
      logo: '/uploads/logo-1679234734506.svg',
    },
  },
  {
    id: 15,
    label: 'Jacket',
    description: 'Desc 1',
    pictures: [product2],
    stock: '1',
    tags: ['asas', 'sasa'],
    createdAt: '2023-03-23T05:58:09.383Z',
    updatedAt: '2023-03-23T05:58:09.383Z',
    details: {
      id: 17,
      price: 1000,
      offered_price: 900,
      currency: 'USD',
      size: 'small',
      condition: 'Poor',
      style: 'casual',
      colour: 'Blue',
      material: 'material-1',
      quantity_type: 'single',
    },
    sub_category: {
      id: 13,
      label: 'test_label',
      description: 'test_description',
      createdAt: '2023-03-19T14:21:59.394Z',
      updatedAt: '2023-03-19T14:21:59.394Z',
    },
    brand: {
      id: 3,
      label: 'Amazon',
      description:
        'Alibaba  connects buyers and sellers worldwide and offers a wide range of products, from consumer goods to industrial machinery.',
      logo: '/uploads/logo-1679234734506.svg',
    },
  },
  {
    id: 17,
    label: 'Stretchable Jeans',
    description: 'Desc 1',
    pictures: [product3],
    stock: '1',
    tags: ['asas', 'sasa'],
    createdAt: '2023-03-23T05:58:09.383Z',
    updatedAt: '2023-03-23T05:58:09.383Z',
    details: {
      id: 17,
      price: 1000,
      offered_price: 900,
      currency: 'USD',
      size: '28',
      condition: 'Poor',
      style: 'casual',
      colour: 'Blue',
      material: 'material-1',
      quantity_type: 'single',
    },
    sub_category: {
      id: 13,
      label: 'test_label',
      description: 'test_description',
      createdAt: '2023-03-19T14:21:59.394Z',
      updatedAt: '2023-03-19T14:21:59.394Z',
    },
    brand: {
      id: 3,
      label: 'Ali Baba',
      description:
        'Alibaba  connects buyers and sellers worldwide and offers a wide range of products, from consumer goods to industrial machinery.',
      logo: '/uploads/logo-1679234734506.svg',
    },
  },
  {
    id: 18,
    label: 'Product Title Here',
    description: 'Desc 1',
    pictures: [product4],
    stock: '1',
    tags: ['asas', 'sasa'],
    createdAt: '2023-03-23T05:58:09.383Z',
    updatedAt: '2023-03-23T05:58:09.383Z',
    details: {
      id: 17,
      price: 1000,
      offered_price: 900,
      currency: 'USD',
      size: 'US 9 | UK 48',
      condition: 'Poor',
      style: 'casual',
      colour: 'Blue',
      material: 'material-1',
      quantity_type: 'single',
    },
    sub_category: {
      id: 13,
      label: 'test_label',
      description: 'test_description',
      createdAt: '2023-03-19T14:21:59.394Z',
      updatedAt: '2023-03-19T14:21:59.394Z',
    },
    brand: {
      id: 3,
      label: 'BRAND NAME',
      description:
        'Alibaba  connects buyers and sellers worldwide and offers a wide range of products, from consumer goods to industrial machinery.',
      logo: '/uploads/logo-1679234734506.svg',
    },
  },
];
export const likedProd = [
  {
    id: 14,
    label: 'Casual Pant',
    description: 'Desc 1',
    pictures: [product1],
    stock: '1',
    tags: ['asas', 'sasa'],
    createdAt: '2023-03-23T05:58:09.383Z',
    updatedAt: '2023-03-23T05:58:09.383Z',
    details: {
      id: 17,
      price: 1000,
      offered_price: 900,
      currency: 'USD',
      size: 'Medium',
      condition: 'Poor',
      style: 'casual',
      colour: 'Blue',
      material: 'material-1',
      quantity_type: 'single',
    },
    sub_category: {
      id: 13,
      label: 'test_label',
      description: 'test_description',
      createdAt: '2023-03-19T14:21:59.394Z',
      updatedAt: '2023-03-19T14:21:59.394Z',
    },
    brand: {
      id: 3,
      label: 'Ali Baba',
      description:
        'Alibaba  connects buyers and sellers worldwide and offers a wide range of products, from consumer goods to industrial machinery.',
      logo: '/uploads/logo-1679234734506.svg',
    },
  },
];
export const purchasedItems = [
  {
    id: 14,
    label: 'Casual Pant',
    description: 'Desc 1',
    pictures: [product1],
    stock: '1',
    tags: ['asas', 'sasa'],
    createdAt: '2023-03-23T05:58:09.383Z',
    updatedAt: '2023-03-23T05:58:09.383Z',
    details: {
      id: 17,
      price: 1000,
      offered_price: 900,
      currency: 'USD',
      size: 'Medium',
      condition: 'Poor',
      style: 'casual',
      colour: 'Blue',
      material: 'material-1',
      quantity_type: 'single',
    },
    sub_category: {
      id: 13,
      label: 'test_label',
      description: 'test_description',
      createdAt: '2023-03-19T14:21:59.394Z',
      updatedAt: '2023-03-19T14:21:59.394Z',
    },
    brand: {
      id: 3,
      label: 'Ali Baba',
      description:
        'Alibaba  connects buyers and sellers worldwide and offers a wide range of products, from consumer goods to industrial machinery.',
      logo: '/uploads/logo-1679234734506.svg',
    },
  },
  {
    id: 18,
    label: 'Product Title Here',
    description: 'Desc 1',
    pictures: [product4],
    stock: '1',
    tags: ['asas', 'sasa'],
    createdAt: '2023-03-23T05:58:09.383Z',
    updatedAt: '2023-03-23T05:58:09.383Z',
    details: {
      id: 17,
      price: 1000,
      offered_price: 900,
      currency: 'USD',
      size: 'US 9 | UK 48',
      condition: 'Poor',
      style: 'casual',
      colour: 'Blue',
      material: 'material-1',
      quantity_type: 'single',
    },
    sub_category: {
      id: 13,
      label: 'test_label',
      description: 'test_description',
      createdAt: '2023-03-19T14:21:59.394Z',
      updatedAt: '2023-03-19T14:21:59.394Z',
    },
    brand: {
      id: 3,
      label: 'BRAND NAME',
      description:
        'Alibaba  connects buyers and sellers worldwide and offers a wide range of products, from consumer goods to industrial machinery.',
      logo: '/uploads/logo-1679234734506.svg',
    },
  },
];

export const SidebarList = [
  { label: 'My Profile', url: '' },
  {
    label: 'My Items for sale',
    subList: [
      { label: 'Active', url: 'mysaleItems?type=public' },
      { label: 'Draft', url: 'mysaleItems?type=draft' },
    ],
  },
  {
    label: 'My Purchases',
    url:'mypurchases'
    // subList: [
    //   { label: 'Pending', url: 'mypurchases?status=pending' },
    //   { label: 'Delivered', url: 'mypurchases?status=delivered' },
    // ],
  },
  { label: 'My Sales', url: 'mysales' },
  { label: 'My Likes', url: 'mylikes' },
  { label: 'My Balance', url: 'mybalance' },
  { label: 'My Closet Insights', url: 'closetinsight' },
  { label: 'My Sale Report', url: 'salereport' },
  { label: 'My Inventory Report', url: 'inventoryreport' },
  { label: 'Invite Friends', url: 'invitefriend' },
];
